CREATE TABLE Usuarios (
    id_usuario SERIAL PRIMARY KEY,
    nombre VARCHAR(100),
    correo VARCHAR(100) UNIQUE,
    contraseña VARCHAR(255),
    rol VARCHAR(20) CHECK (rol IN ('Usuario', 'Administrador')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Empresas (
  id_empresa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100) UNIQUE,
  "direccion" VARCHAR(255),
  "sector" VARCHAR(100),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Evaluaciones (
  id_evaluacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" INT,
  "id_usuario" INT,
  "fecha_evaluacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "puntaje_total" INT,
  "porcentaje_total" FLOAT,
  "resultado" VARCHAR(50)
);

CREATE TABLE Criterios (
  id_criterio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100),
  "descripcion" TEXT,
  "porcentaje" INT,
  norma VARCHAR(20) CHECK (norma IN ('ISO25000', 'IEEE', 'FURPS', 'McCall'))
);

CREATE TABLE DetallesEvaluacion (
  id_detalle_eva INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evaluacion" INT,
  "id_criterio" INT,
  "puntaje" INT,
  "observaciones" TEXT
);

CREATE TABLE MatricesRiesgo (
  id_matriz_ries INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" INT,
  "id_usuario" INT,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DetallesMatrizRiesgo (
  id_detalle_matriz INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_matriz_ries" INT,
  "descripcion_riesgo" TEXT,
  "fase" VARCHAR(100),
  "probabilidad" INT,
  "impacto" INT,
  "nivel_riesgo" VARCHAR(50)
);

CREATE TABLE MatricesMitigacion (
  id_matriz_mitig INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" INT,
  "id_usuario" INT,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DetallesMatrizMitigacion (
  id_detalle_mitig INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_matriz_mitig" INT,
  amenaza_oportunidad VARCHAR(20) CHECK (amenaza_oportunidad IN ('Amenaza', 'Oportunidad')),
  "descripcion_riesgo" TEXT,
  "fase" VARCHAR(100),
  "nivel_riesgo" VARCHAR(50),
  "tipo_respuesta" VARCHAR(100),
  "responsable" VARCHAR(100),
  "plan_mitigacion" TEXT
);

CREATE TABLE PreguntasEvaluacion (
  id_pregunta_evaluacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evaluacion" INT,
  "id_pregunta" INT,
  "id_criterio" INT,
  "respuesta" TEXT
);

CREATE TABLE BancoPreguntas (
  id_pregunta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "texto_pregunta" TEXT,
  norma VARCHAR(20) CHECK (norma IN ('ISO25000', 'IEEE', 'FURPS', 'McCall'))
);

ALTER TABLE Evaluaciones ADD FOREIGN KEY ("id_empresa") REFERENCES Empresas ("id_empresa");

ALTER TABLE Evaluaciones ADD FOREIGN KEY ("id_usuario") REFERENCES Usuarios ("id_usuario");

ALTER TABLE DetallesEvaluacion ADD FOREIGN KEY ("id_evaluacion") REFERENCES Evaluaciones ("id_evaluacion");

ALTER TABLE DetallesEvaluacion ADD FOREIGN KEY ("id_criterio") REFERENCES Criterios ("id_criterio");

ALTER TABLE MatricesRiesgo ADD FOREIGN KEY ("id_empresa") REFERENCES Empresas ("id_empresa");

ALTER TABLE MatricesRiesgo ADD FOREIGN KEY ("id_usuario") REFERENCES Usuarios ("id_usuario");

ALTER TABLE DetallesMatrizRiesgo ADD FOREIGN KEY ("id_matriz_ries") REFERENCES MatricesRiesgo ("id_matriz_ries");

ALTER TABLE MatricesMitigacion ADD FOREIGN KEY ("id_empresa") REFERENCES Empresas ("id_empresa");

ALTER TABLE MatricesMitigacion ADD FOREIGN KEY ("id_usuario") REFERENCES Usuarios ("id_usuario");

ALTER TABLE DetallesMatrizMitigacion ADD FOREIGN KEY ("id_matriz_mitig") REFERENCES MatricesMitigacion ("id_matriz_mitig");

ALTER TABLE PreguntasEvaluacion ADD FOREIGN KEY ("id_evaluacion") REFERENCES Evaluaciones ("id_evaluacion");

ALTER TABLE PreguntasEvaluacion ADD FOREIGN KEY ("id_pregunta") REFERENCES BancoPreguntas ("id_pregunta");

ALTER TABLE PreguntasEvaluacion ADD FOREIGN KEY ("id_criterio") REFERENCES Criterios ("id_criterio");
